### ISSUE TITLE
Native CreateMissionTrain causing crash

### ISSUE THREAD

**Issue by Samnick86** [citizenfx/fivem#1181] opened 2021-12-06 21:03 UTC
Dear Fivem Developers
I tried using the native CreateMissionTrain function and always (after start resource) crashed my fivem client.

I always got this error: Error executing native 0x63c6cca8e68ae8c8
![image](https://user-images.githubusercontent.com/24195059/144917901-ecb95b41-4578-4c2b-b304-d3875016f3c7.png)

I use these train models: freight, freightcar, freightgrain, freightcont1, freightcont2, freighttrailer, tankercar and metrotrain
Models are loaded before use. I don't use trains.xml file, everything is loaded in client.lua

I tried using the same code on my local windows server and I tried it on a linux server.

WIN - Latest optional 5053 build only with 'CFX Default' template
LINUX - Latest optional 5053 build only with 'CFX Default' template

On my windows server the script works, trains are spawned and running. Testet on two diferent computers.

If I use the script on a Linux server and start the script, my client will crash(Error executing native). Server still running. 

I tried the older linux build 3678 with my script and everything was fine, trains are spawned and the player did't got the game crash.

I can't find the reason why on windows builds everything works but only on linux is issue.

**Comment by blattersturm** [comment] 2021-12-06 21:04
Duplicate of #1177.

**Closed by blattersturm** 2021-12-06 21:04 UTC

**Comment by blattersturm** [comment] 2021-12-06 21:07
FYI: you're missing `freightcar2` as the docs say:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/24576130/144922753-552ca270-870a-44ab-a128-632276c91d58.png">

**Comment by blattersturm** [comment] 2021-12-06 21:13
Have a quote from a missing community member:
>Can somebody notify the person(s) spamming my github alerts that:
>
>- Most train scripts have not been updated for 2372/freightcar2, leading to crashes given its not a requested model.
>- freight_config24 was added in 2372, making 'metro_config0' the 25th variant, thus MetroTrain = CreateMissionTrain(24, needs to be updated +1
