### ISSUE TITLE
NetworkAllowLocalEntityAttachment not working since game build 2545

### ISSUE THREAD

**Issue by hojgr** [citizenfx/fivem#1489] opened 2022-06-14 12:26 UTC
NetworkAllowLocalEntityAttachment allows for attaching networked entities to local entities. This works great in game build 2372 and prior, but with game builds 2545 and newer, this function doesn't seem to work as expected.

https://user-images.githubusercontent.com/626096/173575967-5f79ab7a-d1ca-46a8-8b6f-980a34bca19d.mp4
*^ game build 2372*

https://user-images.githubusercontent.com/626096/173576016-f03a969f-93a7-4e85-9911-9f1b8d7053fd.mp4
*^ game build 2545*

Both peds are players, the chair is local entity created by each client respectively.

It can be reproduced with the following code
```lua
local delete = {}

RegisterCommand('attachself', function()
    RequestModel(`v_corp_bk_chair2`)
    local coords = vector3(810.84, -3035.94, 5.74)
    local chair = CreateObject(`v_corp_bk_chair2`, coords.x, coords.y, coords.z, false, false, false)
    table.insert(delete, chair)

    NetworkAllowLocalEntityAttachment(PlayerPedId(), true)
    AttachEntityToEntity(
        PlayerPedId(), chair, 0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, false, false, false, false, 0, true
    )

    while true do
        Wait(0)
        
        i = GetNetworkTimeAccurate()/10

        local offsetPos = vector3(math.cos(math.rad(i)), math.sin(math.rad(i)), 0.0) * 4
        SetEntityCoords(
            chair, 
            coords + offsetPos + vector3(0.0, 0.0, 0.0 + math.sin(i/50)/2),
            false, false, false, false
        )
    end
end, false)

RegisterCommand('fixattach', function(source, args)
    local serverId = tonumber(args[1])

    if not serverId then
        print("ERROR: Usage /fixattach <serverid of player who ran /selfattach")
        return
    end


    local ped = GetPlayerPed(GetPlayerFromServerId(serverId))
    
    local coords = vector3(810.84, -3035.94, 5.74)
    local chair = CreateObject(`v_corp_bk_chair2`, coords.x, coords.y, coords.z, false, false, false)
    table.insert(delete, chair)

    NetworkAllowLocalEntityAttachment(ped, true)
    AttachEntityToEntity(
        ped, chair, 0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, false, false, false, false, 0, true
    )
    
    while true do
        Wait(0)
        
        i = GetNetworkTimeAccurate()/10

        local offsetPos = vector3(math.cos(math.rad(i)), math.sin(math.rad(i)), 0.0) * 4
        SetEntityCoords(
            chair, 
            coords + offsetPos + vector3(0.0, 0.0, 0.0 + math.sin(i/50)/2),
            false, false, false, false
        )

    end
end)

AddEventHandler('onResourceStop', function(name)
    if GetCurrentResourceName() == name then
        for _, b in pairs(delete) do
            DeleteEntity(b)
        end
    end
end)
```

am_rollercoaster.c is doing the same thing for GTA:O rollercoaster

**Comment by hojgr** [comment] 2022-06-14 15:27
@gottfriedleibniz is there something I can do to make it work?

**Comment by blattersturm** [comment] 2022-06-14 15:37
I instructed them to ask here for tracking the repro, we already patch two tunable checks for entity attach: https://github.com/citizenfx/fivem/commit/b21e3edfd9db24331f21d0bdbc3876f31106ee08

**Comment by blattersturm** [comment] 2022-06-26 14:52
I believe the changes fixing this case got merged in by now.

**Closed by blattersturm** 2022-06-26 14:52 UTC

**Comment by draobrehtom** [comment] 2025-03-01 19:14
It looks like the issue is still present. I tested the code samples from the original issue description on game builds 2372 and 3258 and got the same problematic results mentioned in the issue. Could someone from the development team take another look at this?
