### ISSUE TITLE
Upon spawning a bunch of Freemode peds I get down from 80 FPS to 20-30, but when spawning Normal peds with no clothing variation, I don’t get any Frame drops.

### ISSUE THREAD

**Issue by LathiX** [citizenfx/fivem#1336] opened 2022-03-20 12:02 UTC
If you have a lot of players on your server, and the player is standing in a very populated area, and you switch the player into another routing bucket, and back, you get these problems as well!

Upon spawning a bunch of Freemode peds I get down from 80 FPS to 20-30, but when spawning Normal peds with no clothing variation, I don’t get any frame drops.

When I put myself in another session, I get my FPS back, but when I put myself back, FiveM tries to load all of it in, resulting in a HUGE FRAME DROP

I have also found out that, whenever you spawn more than about 34, { FRANKLIN, MICHEAL, TREVOR}, you instantly crash.

If I put every Freemode ped into a different routing bucket, then wait for a little, and put it back, at one time, without a Wait(0) you drop frames, but with a Wait(0) you don’t get almost any!

**Comment by blattersturm** [comment] 2022-03-20 22:50
Duplicate of a forum topic you've posted, that already got replied to:

https://forum.cfx.re/t/huge-fps-drops-upon-spawning-freemode-peds/4828986

**Closed by blattersturm** 2022-03-20 22:50 UTC
