### ISSUE TITLE
Constant crashes after the latest merge

### ISSUE THREAD

**Issue by d22tny** [citizenfx/fivem#3039] opened 2024-12-24 16:55 UTC
### What happened?

The crashes started today, around 4-5 PM. So they are related with the last merge i think.

Here's a dump from my client. The most of my players are playing on canary, so i can provide as much dumps as there are needed.
I told them to switch to release for the moment, but i can get dumps from the staff members.

The crash shows itself as a early exit trap.
The reason the server shows is most likely : (Game crashed: GTA5_b3095.exe!sub_140001E60 (0x0)) or  (Game crashed: GTA5_b3095.exe!??_H@YAXPEAX_KHP6APEAX0@Z@Z (0x0))

[CfxCrashDump_2024_12_24_16_16_35.zip](https://github.com/user-attachments/files/18241025/CfxCrashDump_2024_12_24_16_16_35.zip)

### Expected result

-

### Reproduction steps

-

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

Fivem Canary

**Comment by prikolium-cfx** [comment] 2024-12-24 16:59
Thank you for your report. We are aware of this issue and will push fix a bit later today.

**Comment by prikolium-cfx** [comment] 2024-12-24 17:34
Should be fixed in 4a02b908557591164aeb4bda5929e6f8f310daa1

**Closed by prikolium-cfx** 2024-12-24 17:34 UTC
Labels: bug, triage, crash

**Comment by d22tny** [comment] 2024-12-24 18:11
@prikolium-cfx Crashes still seem to happen.

[CfxCrashDump_2024_12_24_18_10_28.zip](https://github.com/user-attachments/files/18241349/CfxCrashDump_2024_12_24_18_10_28.zip)

Here's a new dump.

![image](https://github.com/user-attachments/assets/a34d855c-de84-4fba-900e-37781dc13054)

Should i open a new issue ?

**Comment by andreiciobanica** [comment] 2024-12-24 18:17
Same here!

![image](https://github.com/user-attachments/assets/6ba8de53-d7aa-465e-bd03-ee212f0e99af)
[CfxCrashDump_2024_12_24_18_16_31.zip](https://github.com/user-attachments/files/18241396/CfxCrashDump_2024_12_24_18_16_31.zip)

**Comment by prikolium-cfx** [comment] 2024-12-24 18:28
It's not related to TU compatibility update. It's duplicate of https://github.com/citizenfx/fivem/issues/3035
