### ISSUE TITLE
FxDK can't load

### ISSUE THREAD

**Issue by bocik1** [citizenfx/fivem#1957] opened 2023-04-25 18:21 UTC
i can't launch FxDK because it is stuck on a loading screen (screen below)
![image](https://user-images.githubusercontent.com/64188833/234367091-17ce61f3-1b09-4cea-8332-ac6a02b5add2.png)

**Comment by bocik1** [comment] 2023-04-25 18:23
i restarted FxDK multiple times and the computer

**Comment by bocik1** [comment] 2023-04-25 18:41
clearing cache fixes it

**Comment by bocik1** [comment] 2023-04-25 18:41
clearing cache fixes it

**Comment by bocik1** [comment] 2023-04-25 18:48
clearing the cache fixes launching but now it can't load a project

**Comment by thorium-cfx** [comment] 2023-04-25 19:32
We don't offer support on here, please see the [forums](https://forum.cfx.re/).

I'll close this as we are unable to look into this issue due to missing reproduction steps and over here FxDK starts normally and loading a project works fine. You can still add the required information and we can reopen this issue.

**Closed by thorium-cfx** 2023-04-25 19:32 UTC
