### ISSUE TITLE
No handler for a loaded player server-side

### ISSUE THREAD

**Issue by xariesnull** [citizenfx/fivem#1491] opened 2022-06-17 16:35 UTC
Hey, for the last time I wanted to solve the problem with cheaters. They turning off the script in the loading screen. The problem is that my anticheat doesn't work because someone can turn it off. Is it possible to add a handler on a server-side that would be triggered after joining a player? Then heartbeats would be profitable to do. The player who cheated on my server showed me how to disable the script in the loading screen where 100% Loaded game or something like this is displayed. My anticheat has an onClientResourceStop handler that works if someone stops the script while it is already loaded on the server.
It would be nice to see such a feature in the future. Regards

**Comment by blattersturm** [comment] 2022-06-17 17:08
Duplicate of #836.

**Closed by blattersturm** 2022-06-17 17:08 UTC
