### ISSUE TITLE
`AddStateBagChangeHandler` triggered twice when state is set from client and replicated

### ISSUE THREAD

**Issue by wtfmozart** [citizenfx/fivem#1791] opened 2023-01-10 00:40 UTC
The handler for the `AddStateBagChangeHandler` is triggered twice the first time the state gets set on the client and is replicated.

Steps to reproduce:
1. Register a command on the client to set the state:
```lua
RegisterCommand('hello', function(source, args, raw)
    LocalPlayer.state:set('hello', 'mom!', true)
end)
```
2. Add a state bag change handler on the client:
```lua
AddStateBagChangeHandler('hello', nil, function(_, _, value)
    print('hello ' .. value) -- prints 'hello mom!' twice
end)
```
2. Load into the server and execute the command.
3. Check the console.

This happens with all the handlers. Which means that you could add handlers for multiple states and all of them will be triggered twice the first time the state, that they are observing, gets updated.
If you also print `GetInvokingResource()` from within the handlers you will notice that it prints the current resource name the first time and `nil` the second time. 
It looks like the server sends the update event back to the client the update originated from.
This happens only the first time you update a given state, so if you execute the command again it will print only once.

Here is a screenshot of the console output, using two handlers for two different states:
![statebag](https://user-images.githubusercontent.com/7603526/211435544-3fe10e91-41c6-4957-8302-8690ffeb177d.png)

**Comment by Korioz** [comment] 2023-01-10 18:24
I don't think this is an issue, if you want it to be called only one time you could just use the `replicated` arg like this
```lua
AddStateBagChangeHandler('hello', nil, function(bagName, key, value, reserved, replicated)
    if replicated then return end
    print('hello ' .. value) -- prints 'hello mom!' one time
end)
```

**Comment by wtfmozart** [comment] 2023-01-10 18:48
@Korioz while that would silence the problem, it is no solution. 
This should be implemented directly inside the artifacts as there is no reason for the handler to be triggered twice. The handler is not called a second time for the consecutive updates for the state, which means that there is a system in place to avoid triggering the handler a second time on the source client, it just needs to be fine-tuned.
For the time being, I will use your method. Thanks for the suggestion!

**Comment by thorium-cfx** [comment] 2023-01-10 23:46
This is intentional, for this reason:

1. Client A updates state bag (triggers local change handler)
2. Client B updates state bag at same-ish time as client A (also triggers local change handler),
3. Server handles Client A's request and relays it to all clients (all clients get client A's changes, triggering their change handler),
4. Server handles Client B's request and relays it to all clients (all clients get client B's changes, triggering their change handler).
5. Everything is up-to-date.

If we would not send the updates back to the requester then in above example; client B would be left with client A's changes, while the server and all other clients are at B's changes.

Changing this behavior requires quite some bookkeeping  and I'm not sure that's worth the resources.

Hope this gives some enlightenment to why it works like this. And as this is not a bug but intended behavior, I'll be closing this issue.

**Closed** 2023-01-10 23:46 UTC
