### ISSUE TITLE
texture not unload when you leave the server.

### ISSUE THREAD

**Issue by V3SC** [citizenfx/fivem#1479] opened 2022-06-05 21:41 UTC
I don't know this is a bug or it was purposely.

if server loaded the texture (example : mphud). It will be always on memory. Even if you leave the server ( not a quit ).

Example Code:

`

> Citizen.CreateThread(function ()
> 	Citizen.Wait(5000)
> 	local texture = "mphud"
> 	if not HasStreamedTextureDictLoaded(texture) then
> 		print('tried to load texture.')
> 		while not HasStreamedTextureDictLoaded(texture) do
> 			print('texture not loaded.')
> 			Citizen.Wait(0)
> 		end
> 	end
> 	while HasStreamedTextureDictLoaded(texture) do
> 		print('texture is already loaded.')
> 		break
> 	end
> end)

`

Code test : https://www.youtube.com/watch?v=JWFycgWMK7I

**Comment by blattersturm** [comment] 2022-06-05 22:06
Are you sure it 'will be always on memory'?

Have you loaded enough other assets during this time to make the game even need to clear any cached in-memory content? If so, and the texture dictionary still remains loaded, that would be a bug as the script txd request doesn't get removed. If not, that isn't a bug but is intended R* game behavior - note that similarly so if you call SET_STREAMED_TEXTURE_DICT_AS_NO_LONGER_NEEDED it also doesn't unload the texture dictionary because again assets remain loaded until the game needs to reclaim memory for other assets.

**Comment by blattersturm** [comment] 2022-06-05 22:27
User confirmed their use case and that this was apparently 'just a question'. Closing as such -> not actionable.

**Closed by blattersturm** 2022-06-05 22:27 UTC
