### ISSUE TITLE
Long 'handshaking with server' after waiting in the main menu

### ISSUE THREAD

**Issue by BerkieBb** [citizenfx/fivem#1454] opened 2022-05-17 18:04 UTC
If you wait for around 3 minutes or longer in the main menu and then join your localhost through the dedicated button for it, it will say 'Handshaking with server' for a much longer time than when you join immediately.
It only seems to happen whenever the server is just started.

**Comment by blattersturm** [comment] 2022-05-17 19:00
Does this happen when connecting using, say, the 'last server' button or F8-connect?

Might be a mDNS thing specific to localhost button discovery if not.

**Comment by BerkieBb** [comment] 2022-05-17 19:33
Just tested the last server button, F8-connect and localhost button again and it only happened at the localhost button

**Comment by akassl-lab** [comment] 2022-05-19 04:19
This isn't just happening with localhost, it's also happening when you want to connect to the last server you've joined. I realize this when developing, you'll open FiveM leave it running for a few minutes and when you focus back into the window and attempt to join a previous server or localhost, it'll stay in the handshaking mode until you decide to terminate the process and re-open it.

**Comment by BerkieBb** [comment] 2022-05-19 05:10
I can't seem to reproduce the issue with the last server button, also, it doesn't keep handshaking, it does it for a much longer time then eventually does connect

**Comment by blattersturm** [comment] 2022-05-21 16:39
This one's tricky to reproduce, as well. I somehow chalked it up to a system issue as each time once restarting, it'd not break 'again' this way until way later, which is also complicating any replication.

It's happened for a little while by now, it's been marked in my todo list for a month or so but then it seemed to not happen anymore so I marked it as 'probably not a bug', earlier I could get it to do this _once_ but then attaching a debugger while stuck showed nothing 'obvious' being stuck, suspicion is there's something in cURL or libuv that doesn't signal an event at times (e.g. because of a backlog of queries from the localhost/last-server button itself refreshing).

**Comment by blattersturm** [comment] 2022-05-22 09:10
I managed to _accidentally_ have it again, it seems cURL is stuck sending the request body at this time.

Curiously, we've been having some issues with the CnL backend service as of ~a month and a bit ago (similar timeframe to this issue) getting saturated with connections that never send the request body, and then subsequently time out, but at times completely break our backend services.

Could this issue actually be occurring _even for our own 'internal' requests, and not just the handshake request?_

**Comment by blattersturm** [comment] 2022-05-22 11:05
The two actually seem unrelated and this is rather introduced in a *server* change: 7cb1c15b3342e5f83d2d01e2946700355ed1f4e2 ("update thread-pool-cpp submodule").

This issue is triggered by a weird race where if a task is posted right when the thread pool is initialized, the work item will never execute and instead wait indefinitely. As there's also some other vague issue on Linux (https://forum.cfx.re/t/http502/4854577), it'd make more sense to back out this library update, and deal with the CPU usage from it slightly spin-waiting for now.

This'd also need a 'recommended' server build update, of course.

**Closed** 2022-05-22 11:24 UTC
