### ISSUE TITLE
Spawning Addon Props - DeSync - on Gamebuild 2944 mp2023_01 San Andreas Mercenaries

### ISSUE THREAD

**Issue by txdaniel55** [citizenfx/fivem#2072] opened 2023-06-26 22:46 UTC
We have tried multiple prop spanner scripts and have no issues with stock props, but on this build Addon Props will spawn but only for the player whom spawns them, not the rest of the server. No issues are dumped to either client or server console. This was not an issue on mpchristmas3.

Server: FXServer 6461
Client: Canary

**Comment by Disquse** [comment] 2023-06-27 15:26
What do you mean by "props"? Can you provide any reproduction steps?

**Comment by gottfriedleibniz** [comment] 2023-06-27 16:38
There are also a few bits of cleanup required in the AttachDataNode parsing bits. There is no need to git-blame this (:

1. [CPedAttachDataNode](https://github.com/citizenfx/fivem/blob/06a1b42d129cd33e2172d98a7d55f147fb13a3d7/code/components/citizen-server-impl/include/state/SyncTrees_Five.h#L2143-L2145) and [CPhysicalAttachDataNode](https://github.com/citizenfx/fivem/blob/06a1b42d129cd33e2172d98a7d55f147fb13a3d7/code/components/citizen-server-impl/include/state/SyncTrees_Five.h#L558-L560) offsets need a build check: `1604/2060: 45.0/40.0, 2189: 75.0/75.0`, and `>=2372: 80.0/80.0`. 
1. The [CPhysicalAttachDataNode](https://github.com/citizenfx/fivem/blob/06a1b42d129cd33e2172d98a7d55f147fb13a3d7/code/components/citizen-server-impl/include/state/SyncTrees_Five.h#L566-L569) quaternion divisor should be `1.0`

**Comment by txdaniel55** [comment] 2023-06-28 00:29
> What do you mean by "props"? Can you provide any reproduction steps?

For example using PlaceObjectOnGroundProperly(x)

prop_compressor_01 will spawn in properly and show for other players, but an addon prop such as: prop_barrier_sign_30, will work properly for the player whom spawned the prop but will not show for any other players and vice versa.

We have tested this using SEM_InteractionMenu and BigDaddy-ObjectSpawner. Both of these scripts produced the same result. When changing ONLY the gamebuild back to mpchristmas3, both scrips and props function properly with the Server Version and Canary Client, but gamebuild mp20223_01 with all the same variables produces this error.

**Comment by ebiggz** [comment] 2023-07-17 18:28
It appears clients will only see objects created by other clients when that object model has been created twice. Subsequent spawns of that object model work fine. It's most apparent in emote resources that attach prop objects to player peds, the emote has to be triggered a second time for other clients to see the prop.

This is the only issue holding me back from being able to update to 2944. I would take a stab at resolving this if I was more familiar with the codebase and confident in the language. Hoping someone much more qualified has the opportunity to work their magic! 🙏🏻

**Comment by gottfriedleibniz** [comment] 2023-07-28 19:40
[createdByOffset](https://github.com/citizenfx/fivem/blob/master/code/components/gta-net-five/src/CloneManager.cpp#L1184) changed to 348 in 2944.

**Comment by Disquse** [comment] 2023-07-28 21:57
@gottfriedleibniz I can confirm this issue is caused by wrong [createdByOffset](https://github.com/citizenfx/fivem/blob/master/code/components/gta-net-five/src/CloneManager.cpp#L1184), thank you, going to be fixed soon.

**Comment by Disquse** [comment] 2023-07-28 22:17
Going to fix the other stuff you're mentioned soon alongside with some other server state related stuff.

**Closed** 2023-07-29 17:56 UTC

**Comment by Forest2357** [comment] 2023-08-13 20:09
I am not sure if that had been reported. I cannot attach any entity to entity.

![Snímek obrazovky 2023-08-13 220835](https://github.com/citizenfx/fivem/assets/103151502/c05f9dc0-cd20-4ea1-b3f4-b7979852c408)
