### ISSUE TITLE
FiveM Node.js need update.

### ISSUE THREAD

**Issue by V3SC** [citizenfx/fivem#2215] opened 2023-09-25 00:24 UTC
Some libraries are not available because FiveM Node.js version is too old. 

![image](https://github.com/citizenfx/fivem/assets/33003717/70230585-96dc-482e-aa54-fa5ab89b242d)

**Comment by nihonium-cfx** [comment] 2023-09-25 08:22
Duplicate of [#2166](https://github.com/citizenfx/fivem/issues/2166)

**Closed by nihonium-cfx** 2023-09-25 08:22 UTC
