### ISSUE TITLE
Serialization of the server object id response failed

### ISSUE THREAD

**Issue by CxCore-xyz** [citizenfx/fivem#2800] opened 2024-09-20 17:16 UTC
### What happened?

People getting crashes from the server but before the crash this message shows in txadmin console.

#Serialization of the server object id response failed. Please report this error at https://github.com/citizenfx/fivem.

### Expected result

No crashes

### Reproduction steps

1. Joined the server
2. Started playing and got crashed

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

3095 linux vps

**Comment by FabianTerhorst** [comment] 2024-09-20 17:18
Duplicate of #2782. Also this is already fixed on latest server builds.

**Closed** 2024-09-20 17:18 UTC
Labels: bug, triage, crash
