### ISSUE TITLE
Crash on closing the Resource Monitor

### ISSUE THREAD

**Issue by BerkieBb** [citizenfx/fivem#1339] opened 2022-03-22 12:01 UTC
I have had this happen to me for about 2 weeks now and only decided to report it now as I thought at first it was a me issue, now that I've reset my PC reinstalled everything after upgrading my hard drive to an ssd and it still happens I thought of reporting it.

I'm currently on the Beta update channel, using game build 2545 and artifact 5411 on my localhost

Here is the crash: 

![image](https://user-images.githubusercontent.com/82737367/159476674-677d890d-415e-4dec-ae1c-a9645844a478.png)

Here is the crash dump:

[CfxCrashDump_2022_03_22_11_55_05.zip](https://github.com/citizenfx/fivem/files/8323943/CfxCrashDump_2022_03_22_11_55_05.zip)

**Comment by blattersturm** [comment] 2022-03-22 12:15
Do you have _any_ reproduction steps for this? This doesn't happen for any system/server we have access to.

**Comment by BerkieBb** [comment] 2022-03-22 12:35
I was able to reproduce this, here are the steps for what I did that crashed me
1. put `use_fxv2_oal 'yes'` in the fxmanifest.lua
2. refresh resources
3. restart the resource
4. open the resource monitor
5. close the resource monitor
The closing and opening were done via the menu at the top of the client console, not via commands

**Comment by Lucas7yoshi** [comment] 2022-03-23 13:47
Reproduced by doing the following:

1. Start resource
2. Open resource monitor
3. Stop resource
4. Close resource monitor using the X button at the top right
5. Crash

Video: https://sx.l7y.ca/2022-03-23_09-36-06.mp4

Also reproduced by doing the following:
1. Open resource monitor
2. Start resource
3. Close resource monitor
4. Crash

No video
Crash Report:
Crash signature: citizen-devtools.dll+13AAC
Report ID: si-5c514e1679304bc8900c1ca3750d3e13

Additional notes:
- I did not get a crash window following the first reproduction
- Seems to be related to the addition or removal of entries in the list?


Given the reputation nvidia drivers have with fivem, hardware may be of relevance:

Ryzen 7 3700x
GTX 1060 6GB - Driver 497.29
Windows 11 Home

**Comment by blattersturm** [comment] 2022-03-24 12:40
> Got another repro
> 
> 1. Open resource monitor before joining server
> 2. Close resource monitor once loaded in
> 3. Crash

I've seen it reported in this way before, but the weird thing indeed is that this _actually doesn't work to repro_ here:

1. I open the game, and write `resmon 1`.
2. I `connect "https://fivem.net/"`, as I was on 1604 before. The same works on 2545, too.
3. Once loaded and spawned, I write `resmon 0`. The game still works.

The same goes for 'start a resource and close'.

**Comment by Lucas7yoshi** [comment] 2022-03-24 12:44
> > Got another repro
> > 
> > 1. Open resource monitor before joining server
> > 2. Close resource monitor once loaded in
> > 3. Crash
> 
> I've seen it reported in this way before, but the weird thing indeed is that this _actually doesn't work to repro_ here:
> 
>     1. I open the game, and write `resmon 1`.
> 
>     2. I `connect "https://fivem.net/"`, as I was on 1604 before. The same works on the other variants (2372, 2545), too, I'm just noting 1604 here as that was my last build.
> 
>     3. Once loaded and spawned, I write `resmon 0`. The game still works, no crash or anything.
> 
> 
> The same goes for 'start a resource and close', as well as other repros mentioned here as they match what I saw in past reports, too.

I am not able to test right now but maybe it's specifically clicking the x button as opposed to closing it by typing resmon 0..?

**Comment by blattersturm** [comment] 2022-03-24 12:44
> but maybe it's specifically clicking the x button as opposed to closing it by typing resmon 0..?

NAK, this also works fine.

**Comment by Lucas7yoshi** [comment] 2022-03-24 12:47
> > but maybe it's specifically clicking the x button as opposed to closing it by typing resmon 0..?
> 
> NAK, this also works fine here

Huh, if there's anything I can do to try and get more information let me know, not sure what more than the crash IDs above could do tho

**Comment by blattersturm** [comment] 2022-03-24 12:55
Report IDs, dumps and stacks here sadly aren't useful, this really seems related to specific resource setup on servers.

Can you check if it works for you on the testing servers?

**Comment by Lucas7yoshi** [comment] 2022-03-24 13:16
I sanity checked on the same server that I initially had it and didn't have a crash. due to the fact I had to remote into my computer to test that I will wait until I am home to properly test it.

**Comment by gottfriedleibniz** [comment] 2022-03-24 13:45
> Close resource monitor using the X button at the top right

Seems like `ResourceMonitorImpl` being destroyed on the Render thread, while OnActive/OnDeactive happening on Main.

**Comment by blattersturm** [comment] 2022-03-24 20:15
> > Close resource monitor using the X button at the top right
> 
> `ResourceMonitor/ResourceMonitorImpl` being destroyed on the Render thread, while OnActive/OnDeactive happening on Main.

Ugh. I somehow really thought this was a shared_ptr.

**Closed** 2022-03-31 19:18 UTC
