### ISSUE TITLE
Adhesive.dll+1239D99  and  Adhesive.dll+ 10D9494

### ISSUE THREAD

**Issue by AstroGirl064** [citizenfx/fivem#2214] opened 2023-09-23 21:40 UTC
Server Version: v1.0.0.6683
Client Verson: Release/Beta/Canary
Game Build: 2944
Server Core: esx-core
Game Crashed for some players  by Adhesive.dll+ 10D9494 and  Adhesive.dll+1239D99

**Comment by Gogsi** [comment] 2023-09-23 21:42
Duplicate of #2211

**Closed** 2023-09-23 21:59 UTC

**Comment by AstroGirl064** [comment] 2023-09-24 01:03
[https://we.tl/t-IoLH051jSt](url)

I think thats it ?
