### ISSUE TITLE
RedM adding custom url protocol.

### ISSUE THREAD

**Issue by Z3rio** [citizenfx/fivem#2065] opened 2023-06-23 14:22 UTC
Would be great to add a custom URL protocol to RedM, just like in FiveM.
So you can connect to servers via URLs.

Example URL from FiveM:
`fivem://connect/11.11.11.11:30120`

**Comment by AvarianKnight** [comment] 2023-06-23 14:46
Duplicate of https://github.com/citizenfx/fivem/issues/1023

**Comment by Z3rio** [comment] 2023-06-24 17:26
> Duplicate of #1023
Yeah, seems to be talking about the same concept.
It doesn't seem to have been active for around 2 years though.

**Comment by Z3rio** [comment] 2023-06-24 17:26
> Duplicate of #1023

Yeah, seems to be talking about the same concept.
It doesn't seem to have been active for around 2 years though.

**Closed** 2023-06-24 19:35 UTC

**Comment by Z3rio** [comment] 2023-10-12 16:05
Yeah, I would love this feature aswell, would open up a lot of possibilities for custom launchers/"portals".

**Comment by Z3rio** [comment] 2023-10-12 16:17
> @Z3rio I know people who do have a RDR2 launcher, but they modified RedM and now they have to maintain their own RedM version.
> 
> Do you know how to compile this (https://github.com/citizenfx/fivem/blob/master/docs/building.md)? Have you done it?

Yeah, I've done that.
I'll have a look at creating a PR for this.

**Comment by SamyOteroGlez** [comment] 2023-10-12 16:32
@Z3rio I am testing a few things locally, this  is what is blocking me now, compiling it.

**Comment by Bobertsawesome** [comment] 2023-10-12 19:21
I originally proposed a method for the URI handling that was basically just copying and editing the fivem URI solution to handle a redm URI. My knowledge of C++ really wasn’t that good and the way I did it left open some weird possibilities for things to bug out. If someone can actually implement correctly I don’t think CFX would be opposed. Building the solution is tricky but following the instructions on the github(?) I was successful. On Oct 12, 2023, at 10:01 AM, SamyOteroGlez ***@***.***> wrote:﻿
Any update/plans to implement this feature in RedM?
There was a PR last year proposing the update (#1580) is there any real plans for this to be implemented?
@Bobertsawesome
