### ISSUE TITLE
Peds are losing their weapons

### ISSUE THREAD

**Issue by spacevx** [citizenfx/fivem#2707] opened 2024-08-12 00:46 UTC
### What happened?

When creating a ped using the server setter and giving a weapon to the ped, if we leave the scope of the ped and re-enter the scope, the ped will lose its weapon. I'm pretty sure @Lucas7yoshi already reported an issue like this on Discord, but I can't remember where

Here is a small video: https://streamable.com/tpyo0b

### Expected result

The ped shouldn't lost his weapon

### Reproduction steps

1. Create a ped server-side.
2. Use statebags to listen for when the ped enters the player's scope.
3. Give the ped a weapon using the native GIVE_WEAPON_TO_PED.
4. Exit the scope of the ped (you need to move far away from the ped).
5. Re-enter the scope of the ped.

### Importancy

Unknown

### Area(s)

FXServer

### Specific version(s)

FiveM v1.0.0.8903 win32

**Comment by ahcenezdh** [comment] 2024-08-12 03:42
Same as #2097

**Comment by ahcenezdh** [comment] 2024-08-12 03:51
I tried to serialize CPedInventoryDataNode, and to use SetupNode but didn't work i probably do something wrong
![image](https://github.com/user-attachments/assets/71ee87f4-67da-4b3b-9d91-175eb671bc7e)

**Comment by Nobelium-cfx** [comment] 2024-12-16 10:02
Closing as a duplicate of https://github.com/citizenfx/fivem/issues/2097 . We can continue work in the original issue.

**Closed by Nobelium-cfx** 2024-12-16 10:02 UTC
Labels: bug, triage
