### ISSUE TITLE
Exports do not work in C#

### ISSUE THREAD

**Issue by JLFSL** [citizenfx/fivem#1742] opened 2022-12-11 10:19 UTC
After hours of attempts and going crazy, I've come to the conclusion that exports from other resources/languages do not seem to work. This occurs with both resources from others and ones I used to test.

The resource is named test.
Example export in Lua
`exports('SayHello', function(str)
  print('Hello, ' .. tostring(str) .. '!')
end)`

Example usage in C#
`Exports["test"].SayHello("test");`

Console log:
```[   2917734] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR in task continuation: System.TypeLoadException: Could not resolve type with token 0100000e^7
[   2917734] [b2699_GTAProce]             MainThrd/ ^3> void Mono.CSharp.ImportedAssemblyDefinition.ReadAttributes()^7 (^5@Emergency/Mono.CSharp.dll^7 <- /mnt/idfk/meow/mono/mcs/mcs/import.cs:1719)
[   2917734] [b2699_GTAProce]             MainThrd/ ^3> IAssemblyDefinition Mono.CSharp.MetadataImporter.GetAssemblyDefinition(Assembly assembly)^7 (^5@Emergency/Mono.CSharp.dll^7 <- /mnt/idfk/meow/mono/mcs/mcs/import.cs:972)
[   2917734] [b2699_GTAProce]             MainThrd/ ^3> void Mono.CSharp.ReflectionImporter.ImportAssembly(Assembly assembly, RootNamespace targetNamespace)^7 (^5@Emergency/Mono.CSharp.dll^7 <- /mnt/idfk/meow/mono/mcs/mcs/reflection.cs:86)
[   2917734] [b2699_GTAProce]             MainThrd/ ^3> DynamicContext Microsoft.CSharp.RuntimeBinder.DynamicContext.Create()^7 (^5@Emergency/Microsoft.CSharp.dll^7 <- /mnt/idfk/meow/mono/mcs/class/Microsoft.CSharp/Microsoft.CSharp.RuntimeBinder/DynamicContext.cs:104)
[   2917734] [b2699_GTAProce]             MainThrd/ ^3> DynamicMetaObject Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion)^7 (^5@Emergency/Microsoft.CSharp.dll^7 <- /mnt/idfk/meow/mono/mcs/class/Microsoft.CSharp/Microsoft.CSharp.RuntimeBinder/CSharpInvokeMemberBinder.cs:156)
[   2917734] [b2699_GTAProce]             MainThrd/ ^3> async void Emergency.Client.LocalPlayer.PlayerManager.SpawnAsync()^7 (^5@Emergency/Emergency.Client.net.dll^7 <- C:\fivem\Server\resources\[emergency]\Emergency\Client\LocalPlayer\PlayerManager.cs:31)
[   2917734] [b2699_GTAProce]             MainThrd/ `

**Comment by blattersturm** [comment] 2022-12-11 10:54
@thorium-cfx might this be an odd regression somewhere?

**Comment by JLFSL** [comment] 2022-12-11 11:11
Maybe some additional logs. This was when I executed the same code as a command like _/test_

```
[    391000] [b2699_GTAProce]             MainThrd/ System.NullReferenceException: Object reference not set to an instance of an object.

[    391000] [b2699_GTAProce]             MainThrd/ 

[    391000] [b2699_GTAProce]             MainThrd/ 

[    391000] [b2699_GTAProce]             MainThrd/ Server stack trace: 

[    391000] [b2699_GTAProce]             MainThrd/   at CitizenFX.Core.InternalManager.PrintError (System.String where, System.Exception what) [0x00081] in C:\gl\builds\master\fivem\code\client\clrcore\InternalManager.cs:595 

[    391000] [b2699_GTAProce]             MainThrd/   at CitizenFX.Core.InternalManager.CallRef (System.Int32 refIndex, System.Byte[] argsSerialized, System.IntPtr& retvalSerialized, System.Int32& retvalSize) [0x000b6] in C:\gl\builds\master\fivem\code\client\clrcore\InternalManager.cs:527 

[    391000] [b2699_GTAProce]             MainThrd/   at (wrapper remoting-invoke-with-check) CitizenFX.Core.InternalManager:CallRef (int,byte[],intptr&,int&)

[    391000] [b2699_GTAProce]             MainThrd/   at (wrapper xdomain-dispatch) CitizenFX.Core.InternalManager:CallRef (object,byte[]&,byte[]&,int,byte[],int&)

[    391000] [b2699_GTAProce]             MainThrd/ 

[    391000] [b2699_GTAProce]             MainThrd/ Exception rethrown at [0]: 

[    391000] [b2699_GTAProce]             MainThrd/   at (wrapper xdomain-invoke) CitizenFX.Core.InternalManager:CallRef (int,byte[],intptr&,int&)

[    391000] [b2699_GTAProce]             MainThrd/   at (wrapper remoting-invoke-with-check) CitizenFX.Core.InternalManager:CallRef (int,byte[],intptr&,int&)

[    391000] [b2699_GTAProce]             MainThrd/   at CitizenFX.Core.MonoScriptRuntime.CallRef (System.Int32 refIndex, System.Byte[] argsSerialized, System.Int32 argsSize, System.IntPtr& retvalSerialized, System.Int32& retvalSize) [0x00013] in C:\gl\builds\master\fivem\code\client\clrcore\MonoScriptRuntime.cs:228 `

**Comment by thorium-cfx** [comment] 2022-12-11 12:37
Was unable to reproduce this with the examples, both client and server give me the `Hello, test!` response. Are there any more details, repro steps?

**Comment by JLFSL** [comment] 2022-12-11 13:43
@thorium-cfx Would it be an idea to share a private repository with the exact code I'm using?

**Comment by JLFSL** [comment] 2022-12-11 13:50
I created an entirely new resource in C# and the function seems to work now strangely. What could a possible reason be for Exports not to be working on my other resources?

**Comment by JLFSL** [comment] 2022-12-11 14:21
If above works, I was able to replicate it this way as well:

If called in another function other than the constructor, it will not work. **Unless**, it was called in the constructor before as so:
```
using CitizenFX.Core;

namespace Example.Client
{
    public class TestClass: BaseScript
    {
        public TestClass()
        {
            Instance = this;

            // Uncomment this line and the Test function will work.
            //Exports["test"].SayHello("testBase");
        }

        public void Test()
        {
            Exports["test"].SayHello("testFunction");
        }
	}
}
```

**Comment by blattersturm** [comment] 2023-03-20 19:45
Closing this until a repro can be provided.

**Closed by blattersturm** 2023-03-20 19:45 UTC
Labels: need info
