### ISSUE TITLE
script error in native 000000008f57a89d: arg[1]: buffer too small (8 < 24) (GetCamMatrix)

### ISSUE THREAD

**Issue by ImBaphomettt** [citizenfx/fivem#3009] opened 2024-12-16 15:37 UTC
### What happened?

It seems that since the latest update, the native function GetCamMatrix is experiencing some issues. Could this be due to improper usage on my part following recent changes, or is it simply an external issue? It was working perfectly fine just yesterday.

![image](https://github.com/user-attachments/assets/af530ffa-8011-4551-ae6a-a131341c628e)

Here is code to reproduce the issue.

```lua
    local cam = CreateCam('DEFAULT_SCRIPTED_CAMERA')
    SetCamCoord(cam, GetEntityCoords(PlayerPedId()))
    SetCamActive(cam, true)
    RenderScriptCams(true, false)
    local rightVector, forwardVector, upVector, position = GetCamMatrix(cam)
    print(rightVector, forwardVector, upVector, position)
```

### Expected result

Native working again.

### Reproduction steps

1. Execute the code client-side and get exeception

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

3258 (canary)

**Comment by ImBaphomettt** [comment] 2024-12-16 15:44
It seems that the following native is also broken: `GetShapeTestResult`.
![image](https://github.com/user-attachments/assets/2a85598d-0a42-4fc0-95e0-f89da8610ddb)

**Comment by d22tny** [comment] 2024-12-16 16:19
```
function Inventory:getVehicleInDirection(coordFrom, coordTo)
	local rayHandle = StartExpensiveSynchronousShapeTestLosProbe(coordFrom.x, coordFrom.y, coordFrom.z, coordTo.x, coordTo.y, coordTo.z, 10, PlayerPedId(), 0)
	local _, _, _, _, vehicle = GetShapeTestResult(rayHandle)

	return vehicle
end
```

--> 
![image](https://github.com/user-attachments/assets/e55788c5-e98a-449e-a08a-5754af0daa94)

```
function FPTOffroad:getNearestRoadDistance()
    local coords = GetEntityCoords(PlayerPedId())
    local ret, srcNode, targetNode, laneCountForward, laneCountBackward, width = GetClosestRoad(coords.x, coords.y, coords.z, 1.0, 0, true)
    local dist1 = #(srcNode - coords)
    local dist2 = #(targetNode - coords)
    return math.min(dist1, dist2)
end
```

--> 
![image](https://github.com/user-attachments/assets/ddab8266-0524-4b74-b48a-46b2f1746d7f)

Also GetModelDimensions also errors out: 

![image](https://github.com/user-attachments/assets/ddb2f563-a182-4c08-a223-60cbed82eda1)

So this seems to be happening on natives that return more than 1 thing.

I think @iridium-cfx could assist in this issue.

**Comment by TheRealBablo** [comment] 2024-12-16 16:24
a temporary fix change branch in your fivem client

**Comment by Mathu-lmn** [comment] 2024-12-16 16:24
Yeah, don't go to canary if you're not testing new features ! Tho I hope they fix this issue ASAP as we all know that many simple players are on the canary release channel !

**Comment by iridium-cfx** [comment] 2024-12-16 16:50
I'm currently unable to reproduce the issue locally, running on the latest canary.

**Comment by d22tny** [comment] 2024-12-16 16:54
@iridium-cfx I'll do the tests right now using the GetClosestRoad native and i'll report back.

**Comment by d22tny** [comment] 2024-12-16 17:03
@iridium-cfx You're right. It doens't happen right away.
Vanilla -> Returns as expected.
All scripts on -> Returns as expected until i spawn a car through my garage, i'll debug further to see what from the spawning function breaks it.

**Comment by Mathu-lmn** [comment] 2024-12-16 17:03
Most likely one of these : 
GetCamMatrix
GetShapeTestResult
GetModelDimensions
GetEntityMatrix
GetClosestFirePos
GetSafeCoordForPed

**Comment by coalaura** [comment] 2024-12-16 17:10
I had the same error pop up on the latest build, beta seems fine. Not sure if its related but i've also had the issue pop up where `GetAspectRatio(false)` appears to return a vector on the latest build but not beta/release

**Comment by Xergxes7** [comment] 2024-12-16 17:15
Getting this issue with following code from ps-inventory:
`local dimensionMin, dimensionMax = GetModelDimensions(GetEntityModel(vehicle))`

![image](https://github.com/user-attachments/assets/155229e5-41c6-43a1-a313-bdb43f8f226a)

**Comment by iridium-cfx** [comment] 2024-12-16 17:19
Ah, I've figured out what the issue is, will hopefully push a fix soon 😅

**Comment by d22tny** [comment] 2024-12-16 17:22
Glad to hear that, i didn't manage to error it on a vanilla server whatsoever :))

**Comment by ImBaphomettt** [comment] 2024-12-16 17:23
> Ah, I've figured out what the issue is, will hopefully push a fix soon 😅

Perfect! I'll let you close the issue when all is well then ! ❤️

**Comment by iridium-cfx** [comment] 2024-12-16 18:12
The fix is merged, let me know if you are still having issues. If not, I'll close the issue tomorrow

**Comment by Psycho66626** [comment] 2024-12-16 18:49
i'm sorry sir, but still the same 😭😭😭
![image](https://github.com/user-attachments/assets/59840c82-ed0f-46d1-808d-cd8d07a2e021)


> The fix is merged, let me know if you are still having issues. If not, I'll close the issue tomorrow

**Comment by Psycho66626** [comment] 2024-12-16 18:54
![image](https://github.com/user-attachments/assets/5563f228-f48f-4542-a525-d4ef6ee3ba40)
and we have faced this debug with all scripts before this print in queue, probably it's 2 in 1

**Comment by Mathu-lmn** [comment] 2024-12-16 18:56
What are you even saying at this point... I can't understand you but the issue on your screenshot was fixed recently, please restart your game to make sure that you're under the correct version and tell us if it happens again

**Comment by Psycho66626** [comment] 2024-12-16 20:06
the same sir `Couldn't load resource sessionmanager: Failed to open packfile: ReadBulk of header failed:`

**Comment by Mathu-lmn** [comment] 2024-12-16 20:08
Again, this is not related to this issue so please join the discord to get support on this issue

**Closed** 2024-12-17 10:08 UTC
Labels: bug, triage, crash
