### ISSUE TITLE
Having awefull issue

### ISSUE THREAD

**Issue by MDGamesmaster** [citizenfx/fivem#2810] opened 2024-09-24 09:47 UTC
### What happened?

this is same before and after complete reinstall of windows. i load fivem, i try to sign in with browser and it opens webpage but wont login when click authorize. when try to login with the normal way through fivem  says my email address already taken and the button to sign in does not highlight. Wont let me connect to a server, and when i try to quit by clicking on the x and then exit the exit button shows im clicking but it does not click. then i do f8 quit and it just hangs. cant even quit through task manager, used fivem for years and never had this

i9 14900k
128mb DDR 5
MSI MAG MB
RTX 3080 TI Founders Edition

### Expected result

the games should work and let me login etc

### Reproduction steps

1, installed windows (did try before and only reinstalled cusz of this error
2, updated windows 11
3, installed steam and the gta
4, installed fivem
5, loaded fivem
6, clicked login via browser, logged in and clicked the orange/red authorize button
7, fivem does nothing when used to login then
8, tried login by enetring email but it comes up like the picture included
![{F58343F1-F286-409D-B10A-3C211656C30A}](https://github.com/user-attachments/assets/4a6dc6e6-e151-4085-813e-ebe2bd5ce4b9)
9, tried to quit by using the x in top right but the only the cancel button not the exit button works
10, pressed f8 and quit that way
11, but then hangs and and cant even get rid through task manager and have to restart pc,

NOTE: worked fine before last update

did try beta aswell

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FIVEM Latest Build

### Additional information

Didnt have none of these issues a month ago. just came to play and wouldnt work. nothing changed on my pc

windows 11 all updated fresh install

**Comment by MDGamesmaster** [comment] 2024-09-24 09:49
![{5BB82A7C-37BC-4615-BAA7-A5F17C5910EB}](https://github.com/user-attachments/assets/5e385fd6-69e3-4a97-b9ec-1fc1102d1bbd)
and even after some time it does quit it leaves all these active

**Comment by nihonium-cfx** [comment] 2024-09-24 09:51
Duplicate of https://github.com/citizenfx/fivem/issues/2786

**Closed by nihonium-cfx** 2024-09-24 09:51 UTC
Labels: bug, triage, crash

**Comment by MDGamesmaster** [comment] 2024-09-24 09:54
that was only part of the issue if you read it all

**Comment by MDGamesmaster** [comment] 2024-09-24 09:55
none of the ui is working correctly aswell. buttons dont click etc, cant login to a server

**Comment by MDGamesmaster** [comment] 2024-09-24 09:58
![{5F2BBF0D-AF0B-4331-8451-7E26B55A2B36}](https://github.com/user-attachments/assets/a801938c-0229-4739-916f-a61aa7476e17)
get this error trying to use canary

**Comment by MDGamesmaster** [comment] 2024-09-24 09:59
[CfxCrashDump_2024_09_24_09_58_51.zip](https://github.com/user-attachments/files/17112477/CfxCrashDump_2024_09_24_09_58_51.zip)

**Comment by MDGamesmaster** [comment] 2024-09-24 10:05
leveldb::VFSEnvironment::LockFile: Failed to create lock file: The process cannot access the file because it is being used by another process.
Error: Opening database (rescache:/) failed: IO error: Could not lock file.

**Comment by MDGamesmaster** [comment] 2024-09-24 10:07
think this is because when quit it wont even let me close the fivem bits from the task manager either, can close other apps fine just the fivem ones just stuck

**Comment by nihonium-cfx** [comment] 2024-09-24 10:13
Next time open separate issues for different problems, please.

The latter error is due to other processes blocking FiveM (the rescache:/ etc.). Kill letfover FiveM process and try again (Press 
Delete for a selected process in the Task Manager). If the problem remains - restarting PC will help with not having leftover processes running.

If you see the same error even after PC restart - there's some other software on your PC accessing FiveM files - we can't help with that.

**Comment by MDGamesmaster** [comment] 2024-09-24 10:15
it was cuz the fivem processes would close. and sorry not used github before
