### ISSUE TITLE
seriallization of ther server object id response failed

### ISSUE THREAD

**Issue by shekibmaroofi** [citizenfx/fivem#2793] opened 2024-09-16 15:10 UTC
### What happened?

players crash 
and in console it says
seriallization of ther server object id response failed
![Screenshot_2024-09-16_151952](https://github.com/user-attachments/assets/d2bc78d4-a9b0-4bf6-aa10-d574bf6e79de)

### Expected result

should normal load players without crashing them

### Reproduction steps

i change back to fx version 7290 it is working but not in new versions 
please help me 

### Importancy

Unknown

### Area(s)

FiveM

### Specific version(s)

Fivem Build server 9875

### Additional information

seriallization of ther server object id response failed

**Comment by FabianTerhorst** [comment] 2024-09-16 15:12
Duplicate of #2782.

**Closed by FabianTerhorst** 2024-09-16 15:12 UTC
Labels: bug, triage
